[project]
name = "service-c"
requires-python = "<=3.9"
version = "0.1.0"
readme = "README.md"
description = ""
dependencies = [
    "flask==2.3.2",
    "pandas==2.1.0"
]

[project.optional-dependencies]
dev = [
    "pytest==7.4.1",
    "mypy==1.5.1"
]
